id: A77666662
title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
  Mountain of Glory'
type: translation
pechas:
- I82ED2A1A
- I01E72077
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:45.891155
  last_modified_at: 2023-01-04 11:47:45.891159
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I82ED2A1A/6220: '6064'
  I01E72077/B212: '6064'
